title:             Zhenqi
email:             1172959695@qq.com
description:       I put my notes in the study period, they are mainly about the deep learning research and implementation. Hope that I can progress together with you.
author:            Zhenqi Sun
# baseurl:           ""
url:               "https://zhenqicool.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
# paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
